# Generated by Django 2.1.5 on 2019-01-09 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20190109_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
