# Generated by Django 2.1.5 on 2019-01-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_ticket_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='plugin_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='hostname',
            field=models.CharField(default='sczepl_testsec5.ad.trw.com', max_length=100, verbose_name='Hostname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ip_address',
            field=models.CharField(default='10.214.75.101', max_length=100, verbose_name='Ip Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='plugin_name',
            field=models.CharField(default='plugin name', max_length=100, verbose_name='Plugin Name'),
            preserve_default=False,
        ),
    ]
