# Generated by Django 2.1.5 on 2019-01-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_auto_20190109_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='plugin_name',
            field=models.CharField(default='Nazwa', max_length=100, verbose_name='Plugin Name'),
        ),
    ]
