# Generated by Django 2.1.5 on 2019-01-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_auto_20190109_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.CharField(default='Blank', max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hostname',
            field=models.CharField(default='Blank', max_length=100, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ip_address',
            field=models.CharField(default='Blank', max_length=100, verbose_name='Ip Address'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='plugin_id',
            field=models.CharField(default='Blank', max_length=100, verbose_name='Plugin ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='plugin_name',
            field=models.CharField(default='Blank', max_length=100, verbose_name='Plugin Name'),
        ),
    ]
